services:
  debricked-scan:
    image: bsha2nk/debricked-scan:latest
    ports:
      - 8080:8080
    networks:
      - debricked-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/debricked-scans
      - spring.rabbitmq.host=rabbitmq
      - jwt-token=
      - status-check-interval=30000
    depends_on:
      mysqldb:
        condition: service_healthy

  debricked-scan-notification:
    image: bsha2nk/debricked-scan-notification:latest
    ports:
      - 8081:8080
    networks:
      - debricked-net
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.mail.username=
      - spring.mail.password=
      - slack-bot-token=
      - slack-channel-id=
      - email-recipient=
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:9.0.1
    ports:
      - 3306:3306
    networks:
      - debricked-net
    volumes:
      - debricked-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 10s
      timeout: 100s
    environment:
      - MYSQL_DATABASE=debricked-scans
      - MYSQL_USER=dbs
      - MYSQL_PASSWORD=dbs
      - MYSQL_ROOT_PASSWORD=root
  
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      debricked-net:


networks:
  debricked-net:


volumes:
  debricked-volume: